name: on-error

dependencies:
  - base
  - exceptions
  - mtl
  - text
  - transformers

library:
  source-dirs: "src"
  exposed-modules:
    - Control.Monad.OnError
    - Control.Monad.Trans.OnError
  other-modules:
    - Control.Monad.Extra
